version: '2.1'

services:
  career-plan:
    # 优先获取该镜像，当不存在的时候，才会利用dockerdockefile构建
    image: career-plan:v1.0
    container_name: career-plan
    build: ./
    volumes:
      - .:/usr/src/app
      - ./logs:/usr/src/app/logs
    ports:
      - "8010:8010"
    environment:
      # 优化： 从外部传入
      # .env 文件，flask可以使用，同时docker-compose也可以从中直接获取环境变量
      FLASK_ENV:
      FLASK_APP:
      SQLALCHEMY_DATABASE_URI:
      REDIS_URI:
      FLASK_SECRET:
      WEBHOOK: