version: '2.1'

services:
  career-plan:
    # 优先获取该镜像，当不存在的时候，才会利用dockerdockefile构建
    image: career-plan:v1.0
    container_name: career-plan
    build: ./
    volumes:
      - ".:/usr/src/app"
    ports:
      - "8010:8010"
    environment:
      # 优化： 从外部传入
      FLASK_ENV:
      FLASK_APP:
      SQLALCHEMY_DATABASE_URI:
      FLASK_SECRET:
      WEBHOOK:
