# -*- coding: utf-8 -*-
# @Time : 2020/11/21
# @Author : Benny Jane
# @Email : 暂无
# @File : tags.py
# @Project : career-planning-info
from collections import namedtuple

Tag_SRC = [
    # ('python', 75),
    ('django', 18),
    ('后端开发', 14),
    ('mysql', 12),
    ('shell', 11),
    ('flask', 10),
    ('java', 10),
    ('linux', 8),
    ('数据库', 6),
    ('redis', 6),
    ('c++', 6),
    ('mongodb', 5),
    ('javascript', 5),
    ('sql', 5),
    ('容器技术', 5),
    ('全栈开发', 4),
    ('网络安全', 4),
    ('postgresql', 4),
    ('大数据', 4),
    ('go', 4),
    ('软件工程师', 3),
    ('git', 3),
    ('tornado', 3),
    ('css', 3),
    ('html', 3),
    ('分布式技术', 3),
    ('web端', 3),
    ('多线程', 2),
    ('机器学习', 2),
    ('爬虫工程师', 2),
    ('计算机软件', 2),
    ('docker', 2),
    ('网络爬虫技术', 2),
    ('scrapy', 2),
    ('saas', 1),
    ('sklearn', 1),
    ('matplotlib', 1),
    ('网络编程', 1),
    ('系统运维', 1),
    ('hadoop', 1),
    ('搜索引擎技术', 1),
    ('全栈', 1),
    ('oracle', 1),
    ('安全行业', 1),
    ('监控系统', 1),
    ('云计算', 1),
    ('数据采集系统', 1),
    ('nosql', 1),
    ('项目管理', 1),
    ('c/c++', 1),
    ('openstack', 1),
    ('虚拟机技术', 1),
    ('bat', 1),
    ('搜索算法', 1),
    ('推荐算法', 1),
    ('numpy', 1),
    ('pandas', 1),
    ('selenium', 1),
    ('ansible', 1),
    ('c#', 1),
    ('perl', 1),
    ('服务器配置', 1),
    ('移动端', 1),
    ('爬虫', 1),
    ('架构师', 1),
    ('数据库开发', 1),
    ('数据挖掘', 1),
    ('it项目管理', 1),
    ('数据分析', 1),
    ('vue', 1)]

tag = namedtuple('tag', 'name bg icon category count')

TAGS = [
    tag("数据库", "info", "1", "mysql/redis/mongodb/postgresql", 32),
    tag("Python的web框架", "info", "2", "django/flask/torando", 31),
    tag("服务器", "primary", "3", "Linux/shell", 19),
    tag("Python库", "primary", "4", "scrapy/pandas/numpy/matplotlib", 5),
    tag("容器技术", "primary", "5", "docker/kubernetes", 5),
    tag("其他", "primary", "6", "大数据/go/分布式技术/多线程等", ""),
]

EXTRAS = [
    "有docker使用经验",
    "有基于容器的集群管理、部署、运维经验",
    "熟练使用异步、并发编程",
    "有分布式编程经验",
    "有开源项目经验",
    "有个人开源项目，最好能超过1K star",
    "了解python生态，会打包发布python软件",
    "了解前端技术",
]
