"""empty message

Revision ID: 5a60da91cb5d
Revises: 
Create Date: 2020-12-15 23:19:49.854992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a60da91cb5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stat_browse',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ip', sa.String(length=120), nullable=True),
    sa.Column('origin', sa.String(length=120), nullable=True, comment='网站视图函数名称'),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stat_info',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ip', sa.String(length=120), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=True, comment='访客行为: like-点赞, download-下载'),
    sa.Column('count', sa.INTEGER(), nullable=True, comment='统计单个IP下载次数'),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True, comment='留言者的邮箱'),
    sa.Column('avatar', sa.Text(), nullable=True, comment='base64格式存储的用户头像'),
    sa.Column('is_admin', sa.Boolean(), nullable=True, comment='是否是网站的管理者'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warning_para',
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('para', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=True, comment='留言内容'),
    sa.Column('reviewed', sa.Boolean(), nullable=True, comment='是否已经被审核'),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('warning_para')
    op.drop_table('user')
    op.drop_table('stat_info')
    op.drop_table('stat_browse')
    # ### end Alembic commands ###
